### ISSUE TITLE
Cryptography fails to build on OpenBSD 6.5.

### ISSUE THREAD

**Issue by chevah-robot** [chevah/compat#156]
T5265 task was created by dumol on 2019-05-06 13:39:09Z.
Last changed on 2019-05-08 12:29:03Z.
PR at https://github.com/chevah/python-package/pull/131.

Ditto, with:

```
    building '_openssl' extension
    creating build/temp.openbsd-6.5-amd64-2.7/build
    creating build/temp.openbsd-6.5-amd64-2.7/build/temp.openbsd-6.5-amd64-2.7
    clang -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -fPIC -I/srv/buildslave/python-package/build/python2.7-openbsd65-x64/include/python2.7 -c build/temp.openbsd-6.5-amd64-2.7/_openssl.c -o build/temp.openbsd-6.5-amd64-2.7/build/temp.openbsd-6.5-amd64-2.7/_openssl.o -Wconversion -Wno-error=sign-conversion
    build/temp.openbsd-6.5-amd64-2.7/_openssl.c:2498:21: error: redefinition of 'DTLS_method' as different kind of symbol
    const SSL_METHOD *(*DTLS_method)(void) = NULL;
                        ^
    /usr/include/openssl/ssl.h:1474:19: note: previous definition is here
    const SSL_METHOD *DTLS_method(void);            /* DTLS v1.0 or later */
                      ^
    build/temp.openbsd-6.5-amd64-2.7/_openssl.c:2499:21: error: redefinition of 'DTLS_server_method' as different kind of symbol
    const SSL_METHOD *(*DTLS_server_method)(void) = NULL;
                        ^
    /usr/include/openssl/ssl.h:1475:19: note: previous definition is here
    const SSL_METHOD *DTLS_server_method(void);     /* DTLS v1.0 or later */
                      ^
    build/temp.openbsd-6.5-amd64-2.7/_openssl.c:2500:21: error: redefinition of 'DTLS_client_method' as different kind of symbol
    const SSL_METHOD *(*DTLS_client_method)(void) = NULL;
                        ^
[…]
```

High prio, because I have upgraded to 6.5 and can't use paver stuff locally.
